import {doctorKey} from './tokens.mjs';
import {selectedVisit,selectedAppointment} from './visit.mjs';
export const STEP_LABELS=['Details','Care team','Identity','Insurance','Documents','Consent','Review'];
export function createPatient(){return {fullName:'',phone:'',email:'',dob:'',facilityId:'',departmentId:'',doctorId:'',slotId:'',emiratesId:'',identityVerified:false,payment:'insurance',insurer:'',policy:'',documents:[],consentData:false,consentRegistration:false};}
export function samplePatient(){return {...createPatient(),fullName:'Sara Ahmed',phone:'+971 50 000 0000',email:'sara@example.com',dob:'1994-06-15',emiratesId:'784-1994-1234567-1',insurer:'Gulf Care (demo insurer)',policy:'DEMO-10428'};}
export function validateStep(patient,step){
 if(step===0){if(patient.fullName.trim().length<2)return 'Enter a patient name.';if(!/^784-\d{4}-\d{7}-\d$/.test(patient.emiratesId))return 'Enter a fictional Emirates ID in the format 784-1994-1234567-1.';if(patient.phone.replace(/\D/g,'').length<9)return 'Enter a phone number with at least 9 digits.';if(!patient.dob||!/^\d{4}-\d{2}-\d{2}$/.test(patient.dob)||patient.dob>new Date().toISOString().slice(0,10))return 'Enter a valid date of birth in the past.';if(patient.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(patient.email))return 'Enter a valid email address or leave it blank.';}
 if(step===1&&!selectedVisit(patient))return 'Select a hospital or clinic, a department and a doctor.';
 if(step===1&&!selectedAppointment(patient))return 'Select an available time slot for your doctor.';
 if(step===2){if(!/^784-\d{4}-\d{7}-\d$/.test(patient.emiratesId))return 'Use the sample Emirates ID format: 784-1994-1234567-1.';if(!patient.identityVerified)return 'Run the simulated identity check to continue.';}
 if(step===3){if(!['insurance','self-pay'].includes(patient.payment))return 'Select a payment option.';if(patient.payment==='insurance'&&(!patient.insurer.trim()||!patient.policy.trim()))return 'Enter the demo insurer and policy number, or select self-pay.';}
 if(step===4&&patient.documents.length===0)return 'Add a sample document or choose a local demonstration file.';
 if(step===5&&(!patient.consentData||!patient.consentRegistration))return 'Accept both demo consent statements to continue.';
 return '';
}
export function verifyIdentity(patient){if(!/^784-\d{4}-\d{7}-\d$/.test(patient.emiratesId))throw new Error('Use the sample Emirates ID format: 784-1994-1234567-1.');patient.identityVerified=true;return {verified:true,simulated:true};}
export function readiness(patient){return Array.from({length:6},(_,i)=>!validateStep(patient,i));}
export function addDocument(patient,file){const name=String(file.name||'');if(!/\.(pdf|png|jpg|jpeg)$/i.test(name))throw new Error('Choose a PDF, PNG or JPG file.');if(file.size>5*1024*1024)throw new Error('Choose a file smaller than 5 MB.');if(patient.documents.length>=5)throw new Error('You can add up to five demo documents.');if(patient.documents.some(d=>d.name===name))throw new Error('This document is already in your list.');patient.documents.push({name,size:Number(file.size)||0,sample:!!file.sample});return {name};}
export function sampleDocuments(patient){for(const file of [{name:'Sample identity document.pdf',size:124000,sample:true},{name:'Sample insurance card.pdf',size:68000,sample:true}]){if(!patient.documents.some(d=>d.name===file.name))addDocument(patient,file);}}
export function initialQueue(){return [{id:'ZQ-1001',name:'Omar Hassan',time:'09:30',department:'General medicine',facility:'ZEITQ Medical Clinic',doctor:'Dr. Aisha Rahman',cabin:'101',arrivalOrder:1,status:'checked-in',payment:'Insurance',source:'Sample'}, {id:'ZQ-1002',name:'Maya Patel',time:'09:45',department:'General medicine',facility:'ZEITQ Medical Clinic',doctor:'Dr. Daniel Thomas',cabin:'102',status:'ready',payment:'Self-pay',source:'Sample'}, {id:'ZQ-1003',name:'Ali Khalid',time:'10:00',department:'General medicine',facility:'ZEITQ Medical Clinic',doctor:'Dr. Aisha Rahman',cabin:'101',status:'review',payment:'Insurance',source:'Sample'}];}
export function submitRegistration(patient,queue,channel='Patient portal'){for(let i=0;i<6;i++){const error=validateStep(patient,i);if(error)throw new Error(error);}const visit=selectedAppointment(patient);const record={id:'ZQ-'+(1004+queue.filter(r=>r.source!=='Sample').length),name:patient.fullName.trim(),time:visit.time,timeLabel:visit.timeLabel,date:visit.date,dateLabel:visit.dateLabel,facility:visit.facility,doctor:visit.doctor,department:visit.department,cabin:visit.cabin,status:'ready',payment:patient.payment==='insurance'?'Insurance':'Self-pay',source:channel,patient:structuredClone(patient)};queue.push(record);return record;}
export function checkIn(queue,id){const record=queue.find(r=>r.id===id);if(!record)throw new Error('Registration not found.');if(record.status!=='ready')throw new Error('This registration is not awaiting check-in.');record.arrivalOrder=Math.max(0,...queue.map(r=>r.arrivalOrder||0))+1;record.status='checked-in';return {id,status:record.status};}
export function callPatient(queue,id){const record=queue.find(r=>r.id===id);if(!record)throw new Error('Registration not found.');if(record.status!=='checked-in')throw new Error('Confirm arrival before calling this patient.');if(queue.some(r=>r.status==='called'&&doctorKey(r)===doctorKey(record)))throw new Error('Complete this doctor’s current consultation before calling another patient.');record.status='called';return {id,status:record.status};}
export function approveReview(queue,id){const record=queue.find(r=>r.id===id);if(!record||record.status!=='review')throw new Error('This registration does not need review.');record.status='ready';return {id,status:record.status};}

export function completeConsultation(queue,id){const record=queue.find(r=>r.id===id);if(!record)throw new Error('Registration not found.');if(record.status!=='called')throw new Error('Only a called token can complete consultation.');record.status='completed';return {id,status:record.status};}
